{% set name = "jupyter_server" %}
{% set version = "1.2.3" %}
{% set sha256 = "d8a723668725be65cc81c2bfe8a805d3e53d26dbe29953cb0fe4d8ae69d71b00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python
    - ipython_genutils
    - jinja2
    - jupyter_core >=4.4.0
    - jupyter_client >=6.1.1
    - nbconvert
    - nbformat
    - pyzmq >=17
    - send2trash
    - terminado >=0.8.3
    - tornado >=6.1
    - traitlets >=4.2.1
    - prometheus_client
    - pywin32 >=1.0  # [win]
    - anyio >=2.0.2
    # TODO: remove after an anyio 2.0.3 comes out so pins work
    - dataclasses  # [py<37]

test:
  requires:
    - pip
  commands:
    - pip check
    - jupyter server -h
  imports:
    - jupyter_server

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Jupyter Server
  description: The Jupyter Server provides the backend for Jupyter web applications such as the Jupyter notebook and JupyterLab.
  dev_url: https://github.com/jupyter/jupyter_server

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - blink1073
    - minrk
    - jasongrout
    - bollwyvl
    - Zsailer
