{% set version = "1.15.1" %}

package:
  name: jupyter_server
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyter_server/jupyter_server-{{ version }}.tar.gz
  sha256: 65fe92c556289990d6b82cbef23d20acb938f6e0b912718af726cbef98229e72

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - jupyter-server = jupyter_server.serverapp:main

requirements:
  host:
    - jupyter-packaging >=0.9,<1
    - pip
    - python >=3.7
  run:
    - anyio >=3.1.0,<4
    - argon2-cffi
    - ipython_genutils
    - jinja2
    - jupyter_client >=6.1.1
    - jupyter_core >=4.6.0
    - nbconvert
    - nbformat
    - packaging
    - prometheus_client
    - python >=3.7
    - pyzmq >=17
    - send2trash
    - terminado >=0.8.3
    - tornado >=6.1.0
    - traitlets >=5
    - websocket-client
  run_constrained:
    - pywinpty <2

test:
  requires:
    - pip
  commands:
    - pip check
    - jupyter server -h
  imports:
    - jupyter_server
  downstreams:
    - jupyterlab >=3.2
    # TODO: uncomment for test suite with deps, etc. when test deps pass pip check
    # - jupyterlab_server >=2.10

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: Jupyter Server
  description: The Jupyter Server provides the backend for Jupyter web applications such as the Jupyter notebook and JupyterLab.
  dev_url: https://github.com/jupyter/jupyter_server
  doc_url: https://jupyter-server.readthedocs.io

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - blink1073
    - minrk
    - jasongrout
    - bollwyvl
    - Zsailer
