# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 2.17.0

package:
  name: jupyter_server
  version: ${{ version }}

source:
  url:
    # prefer the canonical PyPI upload
    - https://pypi.org/packages/source/j/jupyter-server/jupyter_server-${{ version }}.tar.gz
    # fall back to the GitHub release assset (_not_ a snapshot)
    - https://github.com/jupyter-server/jupyter_server/releases/download/v${{ version }}/jupyter_server-${{ version }}.tar.gz
  sha256: c38ea898566964c888b4772ae1ed58eca84592e88251d2cfc4d171f81f7e99d5

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - jupyter-server = jupyter_server.serverapp:main

requirements:
  host:
    - hatch-jupyter-builder >=0.8.1
    - hatchling >=1.11
    - nodejs >=18
    - pip
    - python ${{ python_min }}.*
  run:
    - anyio >=3.1.0
    - argon2-cffi >=21.1
    - jinja2 >=3.0.3
    - jupyter_client >=7.4.4
    - jupyter_core >=4.12,!=5.0.*
    - jupyter_events >=0.11.0
    - jupyter_server_terminals >=0.4.4
    - nbconvert-core >=6.4.4  # avoid hard dependency on pandoc
    - nbformat >=5.3.0
    - overrides >=5.0
    - packaging >=22.0
    - prometheus_client >=0.9
    - python >=${{ python_min }}
    - pyzmq >=24
    - send2trash >=1.8.2
    - terminado >=0.8.3
    - tornado >=6.2.0
    - traitlets >=5.6.0
    - websocket-client >=1.7
    # - pywinpty >=2.0.1  # rely on terminado to get this to keep noarch

tests:
  - python:
      imports: jupyter_server
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - 3.13.*
  - files:
      recipe:
        - run_test.py
      source:
        - tests/
    requirements:
      run:
        - coverage
        - flaky
        - ipykernel
        - pytest >=7.0,<9
        - pytest-console-scripts
        - pytest-cov
        - pytest-timeout
        - pytest-jupyter-server >=0.7
        - python ${{ python_min }}.*
        - requests
    script:
      - jupyter server -h
      - jupyter-server -h
      - python run_test.py
  # TODO: restore downstreams
  # - downstream: jupyterlab >=3.2
  # - downstream: jupyterlab_server >=2.20.0

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: The backend—i.e. core services, APIs, and REST endpoints to Jupyter web applications.
  homepage: https://jupyter-server.readthedocs.io
  repository: https://github.com/jupyter/jupyter_server

extra:
  recipe-maintainers:
    - SylvainCorlay
    - maartenbreddels
    - blink1073
    - minrk
    - jasongrout
    - bollwyvl
    - Zsailer
